### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- Updated to v1.14.3

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Review by yalh76 — CHANGES_REQUESTED** [review]
I have made comments in https://github.com/YunoHost-Apps/kimai2_ynh/pull/37, some have not been implemented before merging in testing.
I think that the testing branch should be trashed and restart the PR from master.

**Comment by frju365** [comment]
mh... I can update the app if you want. @ericgaspar any decision to trash testing and split modifications ?

**Comment by yalh76** [comment]
I will recreate a new testing branch

**Pull request closed without merging**
