### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- Upgrade to 1.19.7
- Fix LDAP #47
- Remove old sqlite support (SQLite is not supported anymore in Kimai2 since version 1.14)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Review by yalh76 — CHANGES_REQUESTED** [review]
As already asked:
https://github.com/YunoHost-Apps/kimai2_ynh/pull/48#issuecomment-1105733945
What will be the consequences for actually running kiamai2 sqlite3 ?

**Comment by yalh76** [comment]
!testme !bullseyetestme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
> ## Problem
> 
>     * _Description of why you made this PR_
> 
> 
> ## Solution
> 
>     * _And how do you fix that problem_
> 
> 

You should give more informations, not letting default stuff

**Comment by ericgaspar** [comment]
> As already asked: [#48 (comment)](https://github.com/YunoHost-Apps/kimai2_ynh/pull/48#issuecomment-1105733945) What will be the consequences for actually running kiamai2 sqlite3 ?

A migration from sqlite to mysql seems not trivial (and out of the scope of kimai2_ynh package)
https://github.com/kevinpapst/kimai2/issues/2484

I don't know how actual Kimai2_ynh user feel about this?

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
> > As already asked: [#48 (comment)](https://github.com/YunoHost-Apps/kimai2_ynh/pull/48#issuecomment-1105733945) What will be the consequences for actually running kiamai2 sqlite3 ?
> 
> A migration from sqlite to mysql seems not trivial (and out of the scope of kimai2_ynh package) [kevinpapst/kimai2#2484](https://github.com/kevinpapst/kimai2/issues/2484)
> 


I don't ask to do a migration from sqlite to mysql ... 
My question is: if a user has a sqlite kimai2_ynh installed, when this PR will be merged in master, his yunohost server will upgrade kimai2_ynh to last version.
What will happened ?

1. the user will keep it's running sqlite kimai2_ynh ?
2. kimai2_ynh will go to mysql and the user will loose all his datas ?
3. kimai2_ynh will be removed ?

**Comment by curious-jeremy** [comment]
> > > As already asked: [#48 (comment)](https://github.com/YunoHost-Apps/kimai2_ynh/pull/48#issuecomment-1105733945) What will be the consequences for actually running kiamai2 sqlite3 ?
> > 
> > 
> > A migration from sqlite to mysql seems not trivial (and out of the scope of kimai2_ynh package) [kevinpapst/kimai2#2484](https://github.com/kevinpapst/kimai2/issues/2484)
> 
> I don't ask to do a migration from sqlite to mysql ... My question is: if a user has a sqlite kimai2_ynh installed, when this PR will be merged in master, his yunohost server will upgrade kimai2_ynh to last version. What will happened ?
> 
>     1. the user will keep it's running sqlite kimai2_ynh ?
> 
>     2. kimai2_ynh will go to mysql and the user will loose all his datas ?
> 
>     3. kimai2_ynh will be removed ?

I just did the test: 
- installed a old kimai2 1.11 with sqlite
- upgraded with branch master
- upgraded with testing branch

=> the last upgrade fails and the backup is restored which results in keeping the app functionnal, using sqlite. No data is lost.

Maybe what should be done is to add a disclaimer explaining that the upgrade will fail in that case.

**Comment by yalh76** [comment]
> I just did the test:
> 
>     * installed a old kimai2 1.11 with sqlite
> 
>     * upgraded with branch master
> 
>     * upgraded with testing branch
> 
> 
> => the last upgrade fails and the backup is restored which results in keeping the app functionnal, using sqlite. No data is lost.
> 
> Maybe what should be done is to add a disclaimer explaining that the upgrade will fail in that case.

It would be better to manage upgrade with sqlite, to let it upgrade to last available version or not doing the upgrade is it's already at the last version.

I don't think that having a failed upgrade with a restore is good way to manage sqlite versions ...

**Comment by ericgaspar** [comment]
Why not build on it instead of deleting everything... I feel like I'm wasting my time here

**Pull request closed without merging**
