### PR TITLE
1.19.7

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- #47

## Solution

- Upgrade to 1.19.7
- Add config panel
- Fix LDAP login
- Remove old sqlite support

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by curious-jeremy** [comment]
I just tested this PR. Here are some feedback:
- Upgrade 1.17.1 -> 1.18.2 :heavy_check_mark: 
    - Once upgraded, LDAP works fine :heavy_check_mark: 
- Upgrade 1.11.1 -> 1.18.2 :negative_squared_cross_mark: 
    - Here are the failing upgrade logs: https://paste.yunohost.org/raw/vamolojebu

**Comment by curious-jeremy** [comment]
Hi :wave: 
Any idea when the upgrade from version 1.11.1 will be fixed?
#47 has been marked as fixed but it actually needs this PR to be merged to be available.
Cheers!

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by yalh76** [comment]
why removing sqlite3 support ?
What will be the consequencies for actually running kiamai2 sqlite3 ?

**Comment by ericgaspar** [comment]
I believe this was a replica prior to mysql use

**Comment by curious-jeremy** [comment]
> why removing sqlite3 support ? What will be the consequencies for actually running kiamai2 sqlite3 ?

SQLite is not supported anymore in Kimai2 since version 1.14

**Comment by heb-dtc** [comment]
looks like we are super close to a fix for that LDAP issue. 
any ideas why the `Install private` test is failing?

**Comment by ericgaspar** [comment]
> looks like we are super close to a fix for that LDAP issue. any idea why the `Install private` test is failing?

This is an ongoing CI bug

**Pull request merged**
